# Site settings
title: Kevin Holmes
description: >
 A website about things both personal, and work related.
 I work in IT and enjoy strength training, bicycling, motorcycling and snowmobiling.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevholmes.github.io" # the base hostname & protocol for your site

author:
  fullname: Kevin Holmes
  googleplus: https://google.com/+KevinHolmesohlala 
  github: kevholmes
  twitter: ElyClover 
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
